### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by BenoitDuffez** [BenoitDuffez/AndroidCupsPrint#21]
Seems to break things:

```
1	|	13:48:48:985	|	D/CrashlyticsCore Failed to check printer PrinterId{serviceName=io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.printservice.CupsService, localId=http://[fe80::da9d:XXXX:XXXX:XXXX]:631/printers/printer}
2	|	13:48:48:986	|	D/CrashlyticsCore HTTP response code: 0
```

Exception:
```
Non-fatal Exception: java.net.MalformedURLException: java.lang.IllegalArgumentException: invalid port: -1
       at java.net.URL.<init>(URL.java:190)
       at java.net.URL.<init>(URL.java:125)
       at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession.checkPrinter(CupsPrinterDiscoverySession.java:163)
       at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession.access$200(CupsPrinterDiscoverySession.java:80)
       at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession$2.doInBackground(CupsPrinterDiscoverySession.java:372)
       at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession$2.doInBackground(CupsPrinterDiscoverySession.java:365)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by BenoitDuffez** [comment]
Seems to be enough.
