### ISSUE TITLE
TypefaceManager.java line 48

### ISSUE THREAD

**Issue by BenoitDuffez** [BenoitDuffez/AndroidCupsPrint#29]
#### in com.github.johnkil.print.TypefaceManager.load

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/upactivity/android/apps/io.github.benoitduffez.cupsprint/issues/586f3c730aeb16625bcf53bd](https://fabric.io/upactivity/android/apps/io.github.benoitduffez.cupsprint/issues/586f3c730aeb16625bcf53bd)

**Comment by BenoitDuffez** [comment]
This is actually raised from this:
https://github.com/johnkil/Print/blob/master/print/src/main/java/com/github/johnkil/print/TypefaceManager.java#L48

```
Fatal Exception: java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: java.lang.RuntimeException: Font asset not found fonts/iconic-font.ttf
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.RuntimeException: Font asset not found fonts/iconic-font.ttf
       at android.graphics.Typeface.createFromAsset(Typeface.java:190)
       at com.github.johnkil.print.TypefaceManager.load(TypefaceManager.java:48)
       at com.github.johnkil.print.PrintConfig.initDefault(PrintConfig.java:35)
       at io.github.benoitduffez.cupsprint.CupsPrintApp.onCreate(CupsPrintApp.java:45)
       at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Closed as it is not linked to this project. Here's the remote issue: https://github.com/johnkil/Print/issues/19
